"""
dictionary with listed TSA checkpoints for each airport by IATA code
"""


checkpoints = {
    'ABE': ['ABE Main Terminal'],
    'ABI': ['ABIA'],
    'ABQ': ['Checkpoint for A/B Gates'],
    'ABR': ['Gate'],
    'ABY': ['ABY-A'],
    'ACK': ['Main Terminal - 1'],
    'ACT': ['ACTA'],
    'ACV': ['ACV01'],
    'ACY': ['Overflow Checkpoint'],
    'ADK': ['Checkpoint1'],
    'ADQ': ['Main Terminal'],
    'AEX': ['AEX01'],
    'AGS': ['AGS-1'],
    'AIA': ['Alliance'],
    'AKN': ['ASAA SCP'],
    'ALB': ['Main Checkpoint'],
    'ALO': ['ALO-1'],
    'ALS': ['Alamosa Airport'],
    'ALW': ['ALW Main'],
    'AMA': ['AMA30'],
    'ANC': ['South Checkpoint'],
    'AOO': ['AOO-01'],
    'APN': ['APN1'],
    'ART': ['Gate Area #1'],
    'ASE': ['Checkpoint 1'],
    'ATL': ['F Arrival Checkpoint','F Departure Checkpoint','Main Checkpoint','New T North Checkpoint','T South Checkpoint'],
    'ATW': ['Checkpoint'],
    'ATY': ['Gate'],
    'AUG': ['Gate 1'],
    'AUS': ['AUS01','AUS02','AUS03','Terminal 2 - South - Main Checkpoint'],
    'AVL': ['AVL-A'],
    'AVP': ['Checkpoint'],
    'AZA': ['IWA01'],
    'AZO': ['Main'],
    'BDL': ['A1','A2'],
    'BET': ['BET-01'],
    'BFD': ['BFD01'],
    'BFF': ['Gate 1 Hold Room'],
    'BFL': ['BFL01'],
    'BFM': ['Checkpoint 1'],
    'BGM': ['0210'],
    'BGR': ['Checkpoint 2'],
    'BHB': ['Gate 1'],
    'BHM': ['Central'],
    'BIL': ['BILM'],
    'BIS': ['Checkpoint A'],
    'BJI': ['Gate'],
    'BKW': ['Checkpoint A'],
    'BLI': ['BLIZ'],
    'BLV': ['Checkpoint A'],
    'BMI': ['Checkpoint A'],
    'BNA': ['BNA Main','Employee Checkpoint','South Checkpoint'],
    'BOI': ['Main Checkpoint'],
    'BOS': ['A1','B1','B5','C2','E2'],
    'BPT': ['BPT01'],
    'BQK': ['Gate'],
    'BQN': ['Rafael Hernandez Air'],
    'BRD': ['Gate'],
    'BRL': ['BRL-1'],
    'BRO': ['BROA'],
    'BRW': ['BRW-01'],
    'BTM': ['BTMZ'],
    'BTR': ['BTR01'],
    'BTV': ['North','South'],
    'BUF': ['Main Checkpoint'],
    'BUR': ['BUR01','BUR02'],
    'BWI': ['Pier A','Pier B','Pier C','Pier D/E','B Checkpoint','D/E Checkpoint'],
    'BZN': ['BZNZ'],
    'CAE': ['CAE-A'],
    'CAK': ['Main'],
    'CDB': ['CDB Checkpoint'],
    'CDR': ['Chadron 1'],
    'CDV': ['Checkpoint CDV-01'],
    'CEC': ['CEC01'],
    'CEZ': ['Cotez-Mun. Cty Arpt'],
    'CGI': ['cape girardeau'],
    'CHA': ['CHA-A'],
    'CHO': ['CHO - Checkpoint'],
    'CHS': ['Checkpoint'],
    'CID': ['Main Concourse'],
    'CIU': ['CIU1'],
    'CKB': ['CKB01'],
    'CLE': ['Central','North','South'],
    'CLL': ['CLL01'],
    'CLT': ['A Checkpoint','B Checkpoint','C Checkpoint','D Checkpoint','E Checkpoint'],
    'CMH': ['A','B','C'],
    'CMI': ['Checkpoint A'],
    'CMX': ['Gate'],
    'CNY': ['CNYZ'],
    'COD': ['COD 01'],
    'COS': ['COS Checkpoint'],
    'COU': ['Gate 1 Hold Area'],
    'CPR': ['CPR 01'],
    'CRP': ['CRP01'],
    'CRW': ['CRW01'],
    'CSG': ['CSG-A'],
    'CVG': ['T3-MCP'],
    'CWA': ['Checkpoint'],
    'DAB': ['DAB A'],
    'DAL': ['Checkpoint'],
    'DAY': ['Main'],
    'DBQ': ['DBQ-1'],
    'DCA': ['Center Pier','Concourse A','North Pier','South Pier'],
    'DDC': ['DDC-1'],
    'DEC': ['Checkpoint A'],
    'DEN': ['A Bridge','North','South'],
    'DFW': ['A12','A21','A35','B30','B9','C10','C21','C30','D18','D22','D30','E16','E18','E33','E8'],
    'DHN': ['DHN-A'],
    'DIK': ['Gate'],
    'DLG': ['DLG-01'],
    'DLH': ['Checkpoint 1'],
    'DRO': ['Checkpoint'],
    'DRT': ['DRT'],
    'DSM': ['Main Concourse'],
    'DTW': ['Blue-1','Blue-2','Red 1','Red 2','Red 3','Red 6'],
    'DUJ': ['DUJ-01'],
    'DVL': ['Checkpoint'],
    'EAR': ['EAR-1'],
    'EAT': ['EAT Main'],
    'EAU': ['Checkpoint'],
    'ECP': ['Checkpoint 1'],
    'EGE': ['Checkpoint'],
    'EKO': ['Checkpoint 1'],
    'ELM': ['Main Checkpoint'],
    'ELP': ['Consolidated Checkpoint'],
    'ERI': ['Main Terminal'],
    'ESC': ['Gate'],
    'EUG': ['EUGZ'],
    'EVV': ['Checkpoint'],
    'EWN': ['Terminal'],
    'EWR': ['Terminal A/1','Terminal A/2','Terminal A/3','Terminal B/1','Terminal B/2','Terminal B/3','Terminal C/1'],
    'EYW': ['MAIN'],
    'FAI': ['ASAA-FAI'],
    'FAR': ['Gate'],
    'FAT': ['FAT 01'],
    'FAY': ['Terminal'],
    'FLG': ['FLG01'],
    'FLL': ['T1 Checkpoint','T2 Checkpoint','T3E Checkpoint','T3F Checkpoint','T4 Checkpoint'],
    'FLO': ['Terminal'],
    'FNT': ['AOO-01'],
    'FOD': ['FOD-1 (1)'],
    'FSD': ['Gate'],
    'FSM': ['FSMA'],
    'FWA': ['Gate'],
    'GCC': ['GCC 01'],
    'GCK': ['GCK-1'],
    'GDV': ['Checkpoint 1'],
    'GEG': ['GEG-A/B','GEGC'],
    'GFK': ['Gate'],
    'GGG': ['GGGA'],
    'GGW': ['Checkpoint 1'],
    'GJT': ['GJTZ'],
    'GLH': ['GLH-A'],
    'GNV': ['GNV A'],
    'GPI': ['Main Checkpoint'],
    'GPT': ['GPT-A'],
    'GRB': ['Concourse A','Concourse B'],
    'GRI': ['GRI-1'],
    'GRK': ['GRK01'],
    'GRR': ['Central Checkpoint'],
    'GSN': ['GSN01'],
    'GSO': ['North Concourse','South Concourse'],
    'GSP': ['Checkpoint'],
    'GTF': ['GTF E/W'],
    'GTR': ['GTR-A'],
    'GUC': ['GUC1'],
    'GUM': ['GUM01'],
    'HDN': ['HDN A'],
    'HGR': ['HGR'],
    'HIB': ['Gate'],
    'HLN': ['HLNZ'],
    'HNL': ['CP 1 Lanes 1&2','CP 1 Lanes 3&4','HNL03','HNL04','HNL05','Makai','Mauka'],
    'HOB': ['Checkpoint 1'],
    'HOU': ['CENTRAL'],
    'HPN': [''],
    'HRL': ['HRL01'],
    'HSV': ['HSV-A'],
    'HTS': ['Main Terminal'],
    'HVN': ['Gate 1'],
    'HVR': ['Checkpoint 1'],
    'HXD': ['Gate'],
    'HYA': ['Gate'],
    'HYS': ['HYS-1'],
    'IAD': ['East Mezzanine','Employee Checkpoint','FIS Checkpoint','Passenger Screening Area: PreCheck','West Mezzanine'],
    'IAG': ['IAG-01'],
    'IAH': ['10/AN Terminal','12/AS Terminal','20/B Terminal','21/B-Employee','30/CN Terminal','31/CS Terminal','40/D Terminal','70/E Terminal','71/FIS Checkpoint'],
    'ICT': ['Wichita Main'],
    'IDA': ['IDAZ'],
    'ILM': ['Terminal'],
    'IMT': ['Gate'],
    'IND': ['Checkpoint A','Checkpoint B'],
    'INL': ['Gate'],
    'IPL': ['IPL01'],
    'IPT': ['Main Checkpoint'],
    'IRK': ['Kirksville'],
    'ISP': ['ISP East'],
    'ITH': ['0240'],
    'ITO': ['ITO01'],
    'IWD': ['Gate'],
    'JAC': ['JAC 01'],
    'JAN': ['JAN-East','JAN-West'],
    'JAX': ['Consolidated Passenger Checkpoint'],
    'JFK': ['Terminal 1','Terminal 2','Terminal 4 Main','Terminal 5','Terminal 7','Terminal 8'],
    'JLN': ['Main Pax Hold Area'],
    'JMS': ['Gate'],
    'JNU': ['JNU-01'],
    'JQF': ['Checkpoint 1'],
    'JST': ['Main Terminal'],
    'KOA': ['KOA01','KOA02'],
    'KTN': ['KTN-01'],
    'LAN': ['Gate'],
    'LAR': ['LAR 01'],
    'LAS': ['Term 1 - AB','Term 1 - C','Term 1 - CX','Term 1 - D','Terminal 3 - E Upper'],
    'LAW': ['LAW01'],
    'LAX': ['Suites','TBIT Main Checkpoint','Terminal 1 - Passenger','Terminal 2 - Passenger','Terminal 3 - Passenger','Terminal 4 - FIS','Terminal 4 - Passenger','Terminal 4A - Passenger','Terminal 5 - Passenger','Terminal 5A - Passenger','Terminal 6 - Passenger','Terminal 7 - Passenger'],
    'LBB': ['LBBA'],
    'LBE': ['Main Terminal'],
    'LBF': ['Gate 1'],
    'LBL': ['LBL-1'],
    'LCH': ['LCH01'],
    'LCK': ['Checkpoint 1'],
    'LEB': ['GATE 1-2'],
    'LEX': ['LEX-A'],
    'LFT': ['LFT01'],
    'LGA': ['TA CHK','TB CHK A','TB CHK B','TB CHK C','TB CHK D','TC CHK East','TC CHK West','TD CHK West'],
    'LGB': ['Checkpoint'],
    'LIH': ['LIH01'],
    'LIT': ['LITA'],
    'LNK': ['North Hold','South Hold'],
    'LNS': ['Cape Air Hold Area'],
    'LNY': ['LNY01'],
    'LRD': ['LRD 01'],
    'LSE': ['Gate'],
    'LWB': ['Main Terminal'],
    'LWS': ['SSC Main'],
    'LYH': ['LYH - Checkpoint'],
    'MAF': ['MAFA'],
    'MBL': ['MBL1'],
    'MBS': ['Passenger Terminal'],
    'MCE': ['Terminal'],
    'MCI': ['MCI 31-35','MCI 37-45','MCI 56-60','MCI 61-69','MCI 76-85'],
    'MCK': ['Gate 1'],
    'MCN': ['MCN-A'],
    'MCO': ['EAST Checkpoint','WEST Checkpoint','WEST FIS'],
    'MCW': ['MCW-1'],
    'MDT': ['MDT Main Terminal'],
    'MDW': ['Main Checkpoint'],
    'MEI': ['MEI-A'],
    'MEM': ['MEM-B','MEM-C'],
    'MFE': ['MFE01'],
    'MFR': ['MFRZ'],
    'MGM': ['MGM-A'],
    'MGW': ['MGW-01'],
    'MHK': ['Main'],
    'MHT': ['Checkpoint'],
    'MIA': ['Central-FA-Upper','Central-G','North 1','North 2','North 3','North FIS','North-E','South-H','South-J1','South-J2'],
    'MKE': ['CONC C','CONC D'],
    'MKG': ['Main Checkpoint'],
    'MKK': ['MKK01'],
    'MLB': ['MLB A'],
    'MLI': ['Checkpoint A'],
    'MLU': ['MLU01'],
    'MMH': ['Checkpoint 1'],
    'MOB': ['MOB-A'],
    'MOT': ['Gate'],
    'MQT': ['Gate'],
    'MRY': ['MRY02'],
    'MSL': ['MSL'],
    'MSN': ['Checkpoint Alpha','Checkpoint Bravo'],
    'MSO': ['Main Security Screen'],
    'MSP': ['Hotel CP','North CP','P-7','South CP','T2 CP1'],
    'MSS': ['Gate Area #1'],
    'MSY': ['MSY01'],
    'MTJ': ['MTJZ'],
    'MVY': ['Gate 1'],
    'MWA': ['Checkpoint A'],
    'MYR': ['Terminal'],
    'NYL': ['YUM01'],
    'OAJ': ['Terminal'],
    'OAK': ['TERM1','TERM2'],
    'OGG': ['OGG01'],
    'OGS': ['Gate Area #1'],
    'OKC': ['Annex','West'],
    'OLF': ['Checkpoint 1'],
    'OMA': ['Terminal A','Terminal B'],
    'OME': ['OME-01'],
    'ONT': ['T2','T4'],
    'ORD': ['1','10','10A','2','3A','4B','5','6','6A','7','7A','8','9'],
    'ORF': ['Conc. A Checkpoint','Conc. B Checkpoint'],
    'ORH': ['Checkpoint 1'],
    'OTH': ['OTHZ'],
    'OTZ': ['OTZ-01'],
    'OWB': ['OWB-A'],
    'PAE': ['PAE Main'],
    'PAH': ['PAH'],
    'PBG': ['Checkpoint 1'],
    'PBI': ['PBI A/B','PBI C'],
    'PDX': ['PDX A/B/C','PDX D/E'],
    'PGA': ['PGA01'],
    'PGD': ['Checkpoint 1'],
    'PGV': ['Terminal'],
    'PHF': ['PHF Checkpoint'],
    'PHL': ['A East','A West Sec 7','Checkpoint B','Checkpoint C','Checkpoint D\E','Checkpoint F'],
    'PHX': ['T-2','T-3 North','T-4 A','T-4 B','T-4 C','T-4 D'],
    'PIA': ['Checkpoint A'],
    'PIB': ['Terminal'],
    'PIE': ['PIE A','PIE B'],
    'PIH': ['PIHZ'],
    'PIR': ['Gate'],
    'PIT': ['Alternate Checkpoint','Main Checkpoint'],
    'PKB': ['Main'],
    'PLN': ['PLN1'],
    'PNS': ['PNS-A'],
    'PQI': ['gate 1'],
    'PRC': ['PRC01'],
    'PSC': ['PSC Main'],
    'PSG': ['PSG-01'],
    'PSM': ['Gate 1'],
    'PSP': ['PSP01'],
    'PUB': ['PUBZ'],
    'PUW': ['PUW Main'],
    'PVC': ['Gate'],
    'PVD': ['Checkpoint A'],
    'PVU': ['Checkpoint 1'],
    'PWM': ['Terminal 2'],
    'RAP': ['1'],
    'RDD': ['RDD01'],
    'RDM': ['RDMZ'],
    'RDU': ['Employee Screening Checkpoint (ESC)','Terminal 1 Checkpoint','Terminal 2 Checkpoint'],
    'RFD': ['Checkpoint A'],
    'RHI': ['MAIN'],
    'RIC': ['RIC Concourse A','RIC Concourse B'],
    'RIW': ['RIW 01'],
    'RKD': ['Gate 1'],
    'RKS': ['RKS 01'],
    'RNO': ['RNO Checkpoint'],
    'ROA': ['ROA01'],
    'ROC': ['Checkpoint'],
    'ROW': ['Checkpoint 1'],
    'RST': ['Main Checkpoint'],
    'RSW': ['Checkpoint B','Checkpoint C','Checkpoint D'],
    'RUT': ['SFB-A'],
    'SAF': ['Checkpoint 1'],
    'SAN': ['CKPT-1','CKPT-2','CKPT-3','CKPT-5','CKPT-6'],
    'SAT': ['SAT01','SAT02'],
    'SAV': ['SAV-A'],
    'SBA': ['SBA01'],
    'SBN': ['A CONC'],
    'SBP': ['SBP01'],
    'SBY': ['SBY01'],
    'SCC': ['SCC-01'],
    'SCK': ['SCK Main Checkpoint'],
    'SDF': ['SDF-A'],
    'SDY': ['Checkpoint 1'],
    'SEA': ['Central Checkpoint','Charlie Checkpoint','FIS Checkpoint','North Checkpoint','South Checkpoint'],
    'SFB': ['SFB-02'],
    'SFO': ['Employee Security Checkpoint D','Employee Security Checkpoint F','Security Checkpoint A','Security Checkpoint B','Security Checkpoint C','Security Checkpoint D','Security Checkpoint F-1','Security Checkpoint F-3','Security Checkpoint G'],
    'SGF': ['Main Checkpoint'],
    'SGU': ['SGUZ'],
    'SHD': ['SHD - Checkpoint'],
    'SHR': ['SHRZ'],
    'SHV': ['Checkpoint SHV01'],
    'SIT': ['SIT-01'],
    'SJC': ['Terminal A','Terminal B North'],
    'SJT': ['SJTA'],
    'SJU': ['Checkpoint 5','Checkpoint BC'],
    'SLC': ['SLC1','SLC2'],
    'SLK': ['0282'],
    'SLN': ['SLN-1'],
    'SMF': ['Central B','Terminal A'],
    'SMX': ['SMX01'],
    'SNA': ['CKPT A','CKPT B','CKPT C'],
    'SOW': ['SOW01'],
    'SPI': ['Checkpoint A'],
    'SPS': ['Checkpoint A'],
    'SRQ': ['SRQ B'],
    'STC': ['Gate'],
    'STL': ['T1-A','T1-C','T2-E','T2-F'],
    'STS': ['STS01'],
    'STT': ['STT B'],
    'STX': ['STX-B'],
    'SUN': ['SUN1'],
    'SUX': ['Main Checkpoint'],
    'SWF': ['Main Checkpoint'],
    'SWO': ['Checkpoint 1'],
    'SYR': ['Central'],
    'TBN': ['Gate 1 Hold Area'],
    'TEX': ['TEXZ'],
    'TLH': ['TLH A'],
    'TOL': ['Checkpoint 1'],
    'TPA': ['TPA A','TPA C','TPA E','TPA F'],
    'TRI': ['TRI-A'],
    'TTN': ['767'],
    'TUL': ['Central Checkpoint'],
    'TUP': ['Terminal'],
    'TUS': ['ACP','BCP','CCP'],
    'TVC': ['TVC1'],
    'TVF': ['Checkpoint'],
    'TWF': ['TWFZ'],
    'TXK': ['TXK01'],
    'TYR': ['TYR01'],
    'TYS': ['Checkpoint 1'],
    'UIN': ['Checkpoint A'],
    'UNV': ['Main Terminal'],
    'VCT': ['VCT01'],
    'VEL': ['VELZ'],
    'VLD': ['VLD-A'],
    'VPS': ['VPS-A'],
    'VRB': ['Checkpoint 1'],
    'WRG': ['WRG-01'],
    'WYS': ['WYSZ'],
    'XNA': ['Checkpoint 2'],
    'XWA': ['Main Checkpoint'],
    'YAK': ['YAK-01'],
    'YKM': ['YKM Main']

}
